import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { cpSync } from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository.
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  // Polyfill import.meta.url so harper.js module init doesn't crash.
  // Value doesn't matter — our code passes a blob URL to BinaryModule.
  define: {
    'import.meta.url': JSON.stringify('file:///unused/'),
  },
  // Don't inline WASM, keep it as a separate file
  loader: {
    ".wasm": "copy",
  },
});

if (prod) {
  await context.rebuild();
  // Copy WASM file to output
  try {
    cpSync(
      "node_modules/harper.js/dist/harper_wasm_bg.wasm",
      "harper_wasm_bg.wasm"
    );
    console.log("Copied WASM file");
  } catch (e) {
    console.warn("Failed to copy WASM file:", e.message);
  }
  process.exit(0);
} else {
  await context.watch();
}
